//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Pirveta
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Список барж.
    /// </summary>
    // *** Start programmer edit section *** (СписокБарж CustomAttributes)

    // *** End programmer edit section *** (СписокБарж CustomAttributes)
    [AutoAltered()]
    [Caption("Список барж")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СписокБаржE", new string[] {
            "НомерБарж as \'Номер барж\'",
            "Производитель as \'Производитель\'"})]
    [View("СписокБаржL", new string[] {
            "НомерБарж as \'Номер барж\'",
            "Производитель as \'Производитель\'"})]
    public class СписокБарж : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомерБарж;
        
        private string fПроизводитель;
        
        // *** Start programmer edit section *** (СписокБарж CustomMembers)

        // *** End programmer edit section *** (СписокБарж CustomMembers)

        
        /// <summary>
        /// НомерБарж.
        /// </summary>
        // *** Start programmer edit section *** (СписокБарж.НомерБарж CustomAttributes)

        // *** End programmer edit section *** (СписокБарж.НомерБарж CustomAttributes)
        public virtual int НомерБарж
        {
            get
            {
                // *** Start programmer edit section *** (СписокБарж.НомерБарж Get start)

                // *** End programmer edit section *** (СписокБарж.НомерБарж Get start)
                int result = this.fНомерБарж;
                // *** Start programmer edit section *** (СписокБарж.НомерБарж Get end)

                // *** End programmer edit section *** (СписокБарж.НомерБарж Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СписокБарж.НомерБарж Set start)

                // *** End programmer edit section *** (СписокБарж.НомерБарж Set start)
                this.fНомерБарж = value;
                // *** Start programmer edit section *** (СписокБарж.НомерБарж Set end)

                // *** End programmer edit section *** (СписокБарж.НомерБарж Set end)
            }
        }
        
        /// <summary>
        /// Производитель.
        /// </summary>
        // *** Start programmer edit section *** (СписокБарж.Производитель CustomAttributes)

        // *** End programmer edit section *** (СписокБарж.Производитель CustomAttributes)
        [StrLen(255)]
        public virtual string Производитель
        {
            get
            {
                // *** Start programmer edit section *** (СписокБарж.Производитель Get start)

                // *** End programmer edit section *** (СписокБарж.Производитель Get start)
                string result = this.fПроизводитель;
                // *** Start programmer edit section *** (СписокБарж.Производитель Get end)

                // *** End programmer edit section *** (СписокБарж.Производитель Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СписокБарж.Производитель Set start)

                // *** End programmer edit section *** (СписокБарж.Производитель Set start)
                this.fПроизводитель = value;
                // *** Start programmer edit section *** (СписокБарж.Производитель Set end)

                // *** End programmer edit section *** (СписокБарж.Производитель Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СписокБаржE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СписокБаржE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СписокБаржE", typeof(IIS.Pirveta.СписокБарж));
                }
            }
            
            /// <summary>
            /// "СписокБаржL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СписокБаржL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СписокБаржL", typeof(IIS.Pirveta.СписокБарж));
                }
            }
        }
    }
}
